name: ovopay
description: "NB Bank - Complete Cross Platform MFS Solution"

publish_to: 'none'

version: 2.1.0+2

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  cupertino_icons: ^1.0.8
  device_info_plus: ^12.2.0
  dio: ^5.8.0+1
  dots_indicator: ^4.0.1
  fast_contacts: ^5.0.1
  file_picker: ^10.1.2
  firebase_core: ^4.2.1
  firebase_messaging: ^16.0.4
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.1.5
  flutter_local_notifications: ^19.1.0
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.4
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.1.0
  flutter_widget_from_html: ^0.17.1
  get: ^4.7.2
  image_picker: ^1.1.2
  intl: ^0.20.2
  local_auth: ^2.3.0
  logger: ^2.5.0
  lottie: ^3.3.1
  mobile_scanner: ^7.0.0
  open_file: ^3.5.10
  path_provider: ^2.1.5
  permission_handler: ^12.0.0
  pin_code_fields: ^8.0.1
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0
  skeletonizer: ^2.1.0+1
  toastification: ^3.0.2
  url_launcher: ^6.3.1

dependency_overrides:
  intl: any
dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/actions/
    - assets/images/onboard/
    - assets/images/logo/
    - assets/animation/
    - assets/fonts/

  fonts:
    - family: AlbertSans
      fonts:
        - asset: assets/fonts/Albert_Sans/AlbertSans-Regular.ttf
        - asset: assets/fonts/Albert_Sans/AlbertSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/Albert_Sans/AlbertSans-Italic.ttf
          style: italic
        - asset: assets/fonts/Albert_Sans/AlbertSans-Light.ttf
          weight: 300
    - family: ocr-a
      fonts:
        - asset: assets/fonts/ocr_a/OCR-A-regular.ttf
